hwi_oauth:
    firewall_names: [main]
    
    resource_owners:
        auth0:
            type: oauth2
            class: 'App\ResourceOwner'
            client_id: "%env(AUTH0_CLIENT_ID)%"
            client_secret: "%env(AUTH0_CLIENT_SECRET)%"
            base_url: "https://%env(AUTH0_DOMAIN)%"
            scope: "openid profile email"

        google:
            type: google
            client_id: "%env(GOOGLE_ID)%"
            client_secret: "%env(GOOGLE_SECRET)%"
            scope: "email profile"